%! evolves_from(+Successor, +Preevolution).
%! evolves_from(+Successor, -Preevolution).
%! evolves_from(-Successor, +Preevolution).
% True if the successor evolves from the preevolution.
% Equal to `evolves_to(Preevolution,Successor)`
% @arg Successor The pokemon evolving from the given preevolution
% @arg Preevolution The pokemon evolving into the given successor
evolves_from(X,Y) :-
  evolves_to(Y,X).

%! evolves_to(+Preevolution, +Successor).
%! evolves_to(+Preevolution, -Successor).
%! evolves_to(-Preevolution, +Successor).
% True if the preevolution evolves into the given successor
% @arg Successor The pokemon evolving from the given preevolution
% @arg Preevolution The pokemon evolving into the given successor
evolves_to(bulbasaur,ivysaur). % <- Kanto-based evolutions from here
evolves_to(ivysaur,venusaur).
evolves_to(charmander,charmeleon).
evolves_to(charmeleon,charizard).
evolves_to(squirtle,wartortle).
evolves_to(wartortle,blastoise).
evolves_to(caterpie,metapod).
evolves_to(metapod,butterfree).
evolves_to(weedle,kakuna).
evolves_to(kakuna,beedrill).
evolves_to(pidgey,pidgeotto).
evolves_to(pidgeotto,pidgeot).
evolves_to(rattata,raticate).
evolves_to(spearow,fearow).
evolves_to(ekans,arbok).
evolves_to(pichu,pikachu).
evolves_to(pikachu,raichu).
evolves_to(sandshrew,sandslash).
evolves_to(nidoran-female,nidorina).
evolves_to(nidorina,nidoqueen).
evolves_to(nidoran-male,nidorino).
evolves_to(nidorino,nidoking).
evolves_to(cleffa,clefairy).
evolves_to(clefairy,clefable).
evolves_to(vulpix,ninetales).
evolves_to(igglybuff,jigglypuff).
evolves_to(jigglypuff,wigglytuff).
evolves_to(zubat,golbat).
evolves_to(golbat,crobat).
evolves_to(oddish,gloom).
evolves_to(gloom,vileplume).
evolves_to(gloom,bellossom).
evolves_to(paras,parasect).
evolves_to(venonat,venomoth).
evolves_to(diglett,dugtrio).
evolves_to(meowth,persian).
evolves_to(psyduck,golduck).
evolves_to(mankey,primeape).
evolves_to(growlithe,arcanine).
evolves_to(poliwag,poliwhirl).
evolves_to(poliwhirl,poliwrath).
evolves_to(poliwhirl,politoed).
evolves_to(abra,kadabra).
evolves_to(kadabra,alakazam).
evolves_to(machop,machoke).
evolves_to(machoke,machamp).
evolves_to(bellsprout,weepinbell).
evolves_to(weepinbell,victreebel).
evolves_to(tentacool,tentacruel).
evolves_to(geodude,graveler).
evolves_to(graveler,golem).
evolves_to(ponyta,rapidash).
evolves_to(slowpoke,slowbro).
evolves_to(slowpoke,slowking).
evolves_to(magnemite,magneton).
evolves_to(magneton,magnezone).
evolves_to(doduo,dodrio).
evolves_to(seel,dewgong).
evolves_to(grimer,muk).
evolves_to(shellder,cloyster).
evolves_to(gastly,haunter).
evolves_to(haunter,gengar).
evolves_to(onix,steelix).
evolves_to(drowzee,hypno).
evolves_to(krabby,kingler).
evolves_to(voltorb,electrode).
evolves_to(exeggcute,exeggutor).
evolves_to(cubone,marowak).
evolves_to(tyrogue,hitmonlee).
evolves_to(tyrogue,hitmonchan).
evolves_to(tyrogue,hitmontop).
evolves_to(lickitung,lickilicky).
evolves_to(koffing,weezing).
evolves_to(rhyhorn,rhydon).
evolves_to(rhydon,rhyperior).
evolves_to(happiny,chansey).
evolves_to(chansey,blissey).
evolves_to(tangela,tangrowth).
evolves_to(horsea,seadra).
evolves_to(seadra,kingdra).
evolves_to(goldeen,seaking).
evolves_to(staryu,starmie).
evolves_to('mime jr.', 'mr. mime').
evolves_to(scyther,scizor).
evolves_to(smoochum,jynx).
evolves_to(elekid,electabuzz).
evolves_to(electabuzz,electivire).
evolves_to(magby,magmar).
evolves_to(magmar,magmortar).
evolves_to(magikarp,gyarados).
evolves_to(eevee,vaporeon).
evolves_to(eevee,jolteon).
evolves_to(eevee,flareon).
evolves_to(eevee,espeon).
evolves_to(eevee,umbreon).
evolves_to(eevee,leafeon).
evolves_to(eevee,glaceon).
evolves_to(eevee,sylveon).
evolves_to(porygon,porygon2).
evolves_to(porygon2,porygon-z).
evolves_to(omanyte,omastar).
evolves_to(kabuto,kabutops).
evolves_to(munchlax,snorlax).
evolves_to(dratini,dragonair).
evolves_to(dragonair,dragonite).
evolves_to(chikorita,bayleef). % <- Johto-based evolutions from here
evolves_to(bayleef,meganium).
evolves_to(cyndaquil,quilava).
evolves_to(quilava,typhlosion).
evolves_to(totodile,croconaw).
evolves_to(croconaw,feraligatr).
evolves_to(sentret,furret).
evolves_to(hoothoot,noctowl).
evolves_to(ledyba,ledian).
evolves_to(spinarak,ariados).
evolves_to(chinchou,lanturn).
evolves_to(togepi,togetic).
evolves_to(togetic,togekiss).
evolves_to(natu,xatu).
evolves_to(mareep,flaaffy).
evolves_to(flaaffy,ampharos).
evolves_to(azurill,marill).
evolves_to(marill,azumarill).
evolves_to(bonsly,sudowoodo).
evolves_to(hoppip,skiploom).
evolves_to(skiploom,jumpluff).
evolves_to(aipom,ambipom).
evolves_to(sunkern,sunflora).
evolves_to(yanma,yanmega).
evolves_to(wooper,quagsire).
evolves_to(murkrow,honchkrow).
evolves_to(misdreavus,mismagius).
evolves_to(wynaut,wobbuffet).
evolves_to(pineco,forretress).
evolves_to(gligar,gliscor).
evolves_to(snubbull,granbull).
evolves_to(sneasel,weavile).
evolves_to(teddiursa,ursaring).
evolves_to(slugma,magcargo).
evolves_to(swinub,piloswine).
evolves_to(piloswine,mamoswine).
evolves_to(remoraid,octillery).
evolves_to(mantyke,mantine).
evolves_to(houndour,houndoom).
evolves_to(phanpy,donphan).
evolves_to(larvitar,pupitar).
evolves_to(pupitar,tyranitar).
evolves_to(treecko,grovyle). % <- Hoenn-based evolutions from here
evolves_to(grovyle,sceptile).
evolves_to(torchic,combusken).
evolves_to(combusken,blaziken).
evolves_to(mudkip,marshtomp).
evolves_to(marshtomp,swampert).
evolves_to(poochyena,mightyena).
evolves_to(zigzagoon,linoone).
evolves_to(wurmple,silcoon).
evolves_to(wurmple,cascoon).
evolves_to(silcoon,beautifly).
evolves_to(cascoon,dustox).
evolves_to(lotad,lombre).
evolves_to(lombre,ludicolo).
evolves_to(seedot,nuzleaf).
evolves_to(nuzleaf,shiftry).
evolves_to(taillow,swellow).
evolves_to(wingull,pelipper).
evolves_to(ralts,kirlia).
evolves_to(kirlia,gardevoir).
evolves_to(kirlia,gallade).
evolves_to(surskit,masquerain).
evolves_to(shroomish,breloom).
evolves_to(slakoth,vigoroth).
evolves_to(vigoroth,slaking).
evolves_to(nincada,ninjask).
evolves_to(nincada,shedinja).
evolves_to(whismur,loudred).
evolves_to(loudred,exploud).
evolves_to(makuhita,hariyama).
evolves_to(nosepass,probopass).
evolves_to(skitty,delcatty).
evolves_to(aron,lairon).
evolves_to(lairon,aggron).
evolves_to(meditite,medicham).
evolves_to(electrike,manectric).
evolves_to(budew,roselia).
evolves_to(roselia,roserade).
evolves_to(gulpin,swalot).
evolves_to(carvanha,sharpedo).
evolves_to(wailmer,wailord).
evolves_to(numel,camerupt).
evolves_to(spoink,grumpig).
evolves_to(trapinch,vibrava).
evolves_to(vibrava,flygon).
evolves_to(cacnea,cacturne).
evolves_to(swablu,altaria).
evolves_to(barboach,whiscash).
evolves_to(corphish,crawdaunt).
evolves_to(baltoy,claydol).
evolves_to(lileep,cradily).
evolves_to(anorith,armaldo).
evolves_to(feebas,milotic).
evolves_to(shuppet,banette).
evolves_to(duskull,dusclops).
evolves_to(dusclops,dusknoir).
evolves_to(chingling,chimecho).
evolves_to(snorunt,glalie).
evolves_to(snorunt,froslass).
evolves_to(spheal,sealeo).
evolves_to(sealeo,walrein).
evolves_to(clamperl,huntail).
evolves_to(clamperl,gorebyss).
evolves_to(bagon,shelgon).
evolves_to(shelgon,salamence).
evolves_to(beldum,metang).
evolves_to(metang,metagross).
evolves_to(turtwig,grotle). % <- Sinnoh-based evolutions from here
evolves_to(grotle,torterra).
evolves_to(chimchar,monferno).
evolves_to(monferno,infernape).
evolves_to(piplup,prinplup).
evolves_to(prinplup,empoleon).
evolves_to(starly,staravia).
evolves_to(staravia,staraptor).
evolves_to(bidoof,bibarel).
evolves_to(kricketot,kricketune).
evolves_to(shinx,luxio).
evolves_to(luxio,luxray).
evolves_to(cranidos,rampardos).
evolves_to(shieldon,bastiodon).
evolves_to(burmy,wormadam).
evolves_to(combee,vespiquen).
evolves_to(buizel,floatzel).
evolves_to(cherubi,cherrim).
evolves_to(shellos,gastrodon).
evolves_to(drifloon,drifblim).
evolves_to(buneary,lopunny).
evolves_to(glameow,purugly).
evolves_to(stunky,skuntank).
evolves_to(bronzor,bronzong).
evolves_to(gible,gabite).
evolves_to(gabite,garchomp).
evolves_to(riolu,lucario).
evolves_to(hippopotas,hippowdon).
evolves_to(skorupi,drapion).
evolves_to(croagunk,toxicroak).
evolves_to(finneon,lumineon).
evolves_to(snover,abomasnow).
evolves_to(snivy,servine). % <- Unova-based evolutions from here
evolves_to(servine,serperior).
evolves_to(tepig,pignite).
evolves_to(pignite,emboar).
evolves_to(oshawott,dewott).
evolves_to(dewott,samurott).
evolves_to(patrat,watchog).
evolves_to(lillipup,herdier).
evolves_to(herdier,stoutland).
evolves_to(purrloin,liepard).
evolves_to(pansage,simisage).
evolves_to(pansear,simisear).
evolves_to(panpour,simipour).
evolves_to(munna,musharna).
evolves_to(pidove,tranquill).
evolves_to(tranquill,unfezant).
evolves_to(blitzle,zebstrika).
evolves_to(roggenrola,boldore).
evolves_to(boldore,gigalith).
evolves_to(woobat,swoobat).
evolves_to(drilbur,excadrill).
evolves_to(timburr,gurdurr).
evolves_to(gurdurr,conkeldurr).
evolves_to(tympole,palpitoad).
evolves_to(palpitoad,seismitoad).
evolves_to(sewaddle,swadloon).
evolves_to(swadloon,leavanny).
evolves_to(venipede,whirlipede).
evolves_to(whirlipede,scolipede).
evolves_to(cottonee,whimsicott).
evolves_to(petilil,lilligant).
evolves_to(sandile,krokorok).
evolves_to(krokorok,krookodile).
evolves_to(darumaka,darmanitan).
evolves_to(dwebble,crustle).
evolves_to(scraggy,scrafty).
evolves_to(yamask,cofagrigus).
evolves_to(tirtouga,carracosta).
evolves_to(archen,archeops).
evolves_to(trubbish,garbodor).
evolves_to(zorua,zoroark).
evolves_to(minccino,cinccino).
evolves_to(gothita,gothorita).
evolves_to(gothorita,gothitelle).
evolves_to(solosis,duosion).
evolves_to(duosion,reuniclus).
evolves_to(ducklett,swanna).
evolves_to(vanillite,vanillish).
evolves_to(vanillish,vanilluxe).
evolves_to(deerling,sawsbuck).
evolves_to(karrablast,escavalier).
evolves_to(foongus,amoonguss).
evolves_to(frillish,jellicent).
evolves_to(joltik,galvantula).
evolves_to(ferroseed,ferrothorn).
evolves_to(klink,klang).
evolves_to(klang,klinklang).
evolves_to(tynamo,eelektrik).
evolves_to(eelektrik,eelektross).
evolves_to(elgyem,beheeyem).
evolves_to(litwick,lampent).
evolves_to(lampent,chandelure).
evolves_to(axew,fraxure).
evolves_to(fraxure,haxorus).
evolves_to(cubchoo,beartic).
evolves_to(shelmet,accelgor).
evolves_to(mienfoo,mienshao).
evolves_to(golett,golurk).
evolves_to(pawniard,bisharp).
evolves_to(rufflet,braviary).
evolves_to(vullaby,mandibuzz).
evolves_to(deino,zweilous).
evolves_to(zweilous,hydreigon).
evolves_to(larvesta,volcarona).
evolves_to(chespin,quilladin). % <- Kalos-based evolutions from here
evolves_to(quilladin,chesnaught).
evolves_to(fennekin,braixen).
evolves_to(braixen,delphox).
evolves_to(froakie,frogadier).
evolves_to(frogadier,greninja).
evolves_to(bunnelby,diggersby).
evolves_to(fletchling,fletchinder).
evolves_to(fletchinder,talonflame).
evolves_to(scatterbug,spewpa).
evolves_to(spewpa,vivillon).
evolves_to(litleo,pyroar).
evolves_to(flabebe,floette).
evolves_to(floette,florges).
evolves_to(skiddo,gogoat).
evolves_to(pancham,pangoro).
evolves_to(espurr,meowstic).
evolves_to(honedge,doublade).
evolves_to(doublade,aegislash).
evolves_to(spritzee,aromatisse).
evolves_to(swirlix,slurpuff).
evolves_to(inkay,malamar).
evolves_to(binacle,barbaracle).
evolves_to(skrelp,dragalge).
evolves_to(clauncher,clawitzer).
evolves_to(helioptile,heliolisk).
evolves_to(tyrunt,tyrantrum).
evolves_to(amaura,aurorus).
evolves_to(goomy,sliggoo).
evolves_to(sliggoo,goodra).
evolves_to(phantump,trevenant).
evolves_to(pumpkaboo,gourgeist).
evolves_to(bergmite,avalugg).
evolves_to(noibat,noivern).
