%! item(+Name, +Fling_power, +Fling_effect).
% @arg Name The name of the item
% @arg Fling_power The power the move `fling` has, if this item is hold
% @arg Fling_effect The effect the move `fling` has, if this item is hold
item(master-ball,nil,[]).
item(ultra-ball,nil,[]).
item(great-ball,nil,[]).
item(poke-ball,nil,[]).
item(safari-ball,nil,[]).
item(net-ball,nil,[]).
item(dive-ball,nil,[]).
item(nest-ball,nil,[]).
item(repeat-ball,nil,[]).
item(timer-ball,nil,[]).
item(luxury-ball,nil,[]).
item(premier-ball,nil,[]).
item(dusk-ball,nil,[]).
item(heal-ball,nil,[]).
item(quick-ball,nil,[]).
item(cherish-ball,nil,[]).
item(potion,30,[]).
item(antidote,30,[]).
item(burn-heal,30,[]).
item(ice-heal,30,[]).
item(awakening,30,[]).
item(paralyze-heal,30,[]).
item(full-restore,30,[]).
item(max-potion,30,[]).
item(hyper-potion,30,[]).
item(super-potion,30,[]).
item(full-heal,30,[]).
item(revive,30,[]).
item(max-revive,30,[]).
item(fresh-water,30,[]).
item(soda-pop,30,[]).
item(lemonade,30,[]).
item(moomoo-milk,30,[]).
item(energy-powder,30,[]).
item(energy-root,30,[]).
item(heal-powder,30,[]).
item(revival-herb,30,[]).
item(ether,30,[]).
item(max-ether,30,[]).
item(elixir,30,[]).
item(max-elixir,30,[]).
item(lava-cookie,30,[]).
item(berry-juice,30,[]).
item(sacred-ash,30,[]).
item(hp-up,30,[]).
item(protein,30,[]).
item(iron,30,[]).
item(carbos,30,[]).
item(calcium,30,[]).
item(rare-candy,30,[]).
item(pp-up,30,[]).
item(zinc,30,[]).
item(pp-max,30,[]).
item(old-gateau,30,[]).
item(guard-spec,30,[]).
item(dire-hit,30,[]).
item(x-attack,30,[]).
item(x-defense,30,[]).
item(x-speed,30,[]).
item(x-accuracy,30,[]).
item(x-sp-atk,30,[]).
item(x-sp-def,30,[]).
item(poke-doll,30,[]).
item(fluffy-tail,30,[]).
item(blue-flute,30,[]).
item(yellow-flute,30,[]).
item(red-flute,30,[]).
item(black-flute,30,[]).
item(white-flute,30,[]).
item(adamant-orb,60,[]).
item(lustrous-orb,60,[]).
item(cheri-berry,10,[fling_berry]).
item(chesto-berry,10,[fling_berry]).
item(pecha-berry,10,[fling_berry]).
item(rawst-berry,10,[fling_berry]).
item(aspear-berry,10,[fling_berry]).
item(leppa-berry,10,[fling_berry]).
item(oran-berry,10,[fling_berry]).
item(persim-berry,10,[fling_berry]).
item(lum-berry,10,[fling_berry]).
item(sitrus-berry,10,[fling_berry]).
item(figy-berry,10,[fling_berry]).
item(wiki-berry,10,[fling_berry]).
item(mago-berry,10,[fling_berry]).
item(aguav-berry,10,[fling_berry]).
item(iapapa-berry,10,[fling_berry]).
item(occa-berry,10,[]).
item(passho-berry,10,[]).
item(wacan-berry,10,[]).
item(rindo-berry,10,[]).
item(yache-berry,10,[]).
item(chople-berry,10,[]).
item(kebia-berry,10,[]).
item(shuca-berry,10,[]).
item(coba-berry,10,[]).
item(payapa-berry,10,[]).
item(tanga-berry,10,[]).
item(charti-berry,10,[]).
item(kasib-berry,10,[]).
item(haban-berry,10,[]).
item(colbur-berry,10,[]).
item(babiri-berry,10,[]).
item(chilan-berry,10,[]).
item(liechi-berry,10,[fling_berry]).
item(ganlon-berry,10,[fling_berry]).
item(salac-berry,10,[fling_berry]).
item(petaya-berry,10,[fling_berry]).
item(apicot-berry,10,[fling_berry]).
item(lansat-berry,10,[fling_berry]).
item(starf-berry,10,[fling_berry]).
item(enigma-berry,10,[]).
item(micle-berry,10,[fling_berry]).
item(custap-berry,10,[]).
item(jaboca-berry,10,[]).
item(rowap-berry,10,[]).
item(bright-powder,10,[]).
item(white-herb,10,[fling_herb]).
item(macho-brace,60,[]).
item(exp-share,30,[]).
item(quick-claw,80,[]).
item(soothe-bell,10,[]).
item(mental-herb,10,[fling_herb]).
item(choice-band,10,[]).
item(kings-rock,30,[flinch(always)]).
item(silver-powder,10,[]).
item(amulet-coin,30,[]).
item(cleanse-tag,30,[]).
item(soul-dew,30,[]).
item(deep-sea-tooth,90,[]).
item(deep-sea-scale,30,[]).
item(smoke-ball,30,[]).
item(everstone,30,[]).
item(focus-band,10,[]).
item(lucky-egg,30,[]).
item(scope-lens,30,[]).
item(metal-coat,30,[]).
item(leftovers,10,[]).
item(light-ball,30,[ailment(paralysis,always)]).
item(soft-sand,10,[]).
item(hard-stone,100,[]).
item(miracle-seed,30,[]).
item(black-glasses,30,[]).
item(black-belt,30,[]).
item(magnet,30,[]).
item(mystic-water,30,[]).
item(sharp-beak,50,[]).
item(poison-barb,70,[ailment(poison,always)]).
item(never-melt-ice,30,[]).
item(spell-tag,30,[]).
item(twisted-spoon,30,[]).
item(charcoal,30,[]).
item(dragon-fang,70,[]).
item(silk-scarf,10,[]).
item(shell-bell,30,[]).
item(sea-incense,10,[]).
item(lax-incense,10,[]).
item(lucky-punch,40,[]).
item(metal-powder,10,[]).
item(thick-club,90,[]).
item(stick,60,[]).
item(red-scarf,10,[]).
item(blue-scarf,10,[]).
item(pink-scarf,10,[]).
item(green-scarf,10,[]).
item(yellow-scarf,10,[]).
item(wide-lens,10,[]).
item(muscle-band,10,[]).
item(wise-glasses,10,[]).
item(expert-belt,10,[]).
item(light-clay,30,[]).
item(life-orb,30,[]).
item(power-herb,10,[]).
item(toxic-orb,30,[ailment(bad-poison,always)]).
item(flame-orb,30,[ailment(burn,always)]).
item(quick-powder,10,[]).
item(focus-sash,10,[]).
item(zoom-lens,10,[]).
item(metronome,30,[]).
item(iron-ball,130,[]).
item(lagging-tail,10,[]).
item(destiny-knot,10,[]).
item(black-sludge,30,[]).
item(icy-rock,40,[]).
item(smooth-rock,10,[]).
item(heat-rock,60,[]).
item(damp-rock,60,[]).
item(grip-claw,90,[]).
item(choice-scarf,10,[]).
item(sticky-barb,80,[]).
item(power-bracer,70,[]).
item(power-belt,70,[]).
item(power-lens,70,[]).
item(power-band,70,[]).
item(power-anklet,70,[]).
item(power-weight,70,[]).
item(shed-shell,10,[]).
item(big-root,10,[]).
item(choice-specs,10,[]).
item(flame-plate,90,[]).
item(splash-plate,90,[]).
item(zap-plate,90,[]).
item(meadow-plate,90,[]).
item(icicle-plate,90,[]).
item(fist-plate,90,[]).
item(toxic-plate,90,[]).
item(earth-plate,90,[]).
item(sky-plate,90,[]).
item(mind-plate,90,[]).
item(insect-plate,90,[]).
item(stone-plate,90,[]).
item(spooky-plate,90,[]).
item(draco-plate,90,[]).
item(dread-plate,90,[]).
item(iron-plate,90,[]).
item(odd-incense,10,[]).
item(rock-incense,10,[]).
item(full-incense,10,[]).
item(wave-incense,10,[]).
item(rose-incense,10,[]).
item(luck-incense,10,[]).
item(pure-incense,10,[]).
item(razor-claw,80,[]).
item(razor-fang,30,[flinch(always)]).
