%! pokemon_form(+Pokemon_form, +Tag).
%
% Helps distinguishing between pokemon form variations.
%
% There are certein pokemon forms that can be used to build a team with, like the
% different Rotom variation. But also there are forms only accessable in a battle,
% like Aegislash's blade form.
%
% This predicate serves as quick reference, as if tags a form with either
% `default` for forms being accessable form outside of a battle or `battle_only`
% @arg Pokemon_form A pokemon form name
% @arg Tag Either `default` or `battle_only`
pokemon_form(bulbasaur,default).
pokemon_form(ivysaur,default).
pokemon_form(venusaur,default).
pokemon_form(charmander,default).
pokemon_form(charmeleon,default).
pokemon_form(charizard,default).
pokemon_form(squirtle,default).
pokemon_form(wartortle,default).
pokemon_form(blastoise,default).
pokemon_form(caterpie,default).
pokemon_form(metapod,default).
pokemon_form(butterfree,default).
pokemon_form(weedle,default).
pokemon_form(kakuna,default).
pokemon_form(beedrill,default).
pokemon_form(pidgey,default).
pokemon_form(pidgeotto,default).
pokemon_form(pidgeot,default).
pokemon_form(rattata,default).
pokemon_form(raticate,default).
pokemon_form(spearow,default).
pokemon_form(fearow,default).
pokemon_form(ekans,default).
pokemon_form(arbok,default).
pokemon_form(pikachu,default).
pokemon_form(raichu,default).
pokemon_form(sandshrew,default).
pokemon_form(sandslash,default).
pokemon_form(nidoran-f,default).
pokemon_form(nidorina,default).
pokemon_form(nidoqueen,default).
pokemon_form(nidoran-m,default).
pokemon_form(nidorino,default).
pokemon_form(nidoking,default).
pokemon_form(clefairy,default).
pokemon_form(clefable,default).
pokemon_form(vulpix,default).
pokemon_form(ninetales,default).
pokemon_form(jigglypuff,default).
pokemon_form(wigglytuff,default).
pokemon_form(zubat,default).
pokemon_form(golbat,default).
pokemon_form(oddish,default).
pokemon_form(gloom,default).
pokemon_form(vileplume,default).
pokemon_form(paras,default).
pokemon_form(parasect,default).
pokemon_form(venonat,default).
pokemon_form(venomoth,default).
pokemon_form(diglett,default).
pokemon_form(dugtrio,default).
pokemon_form(meowth,default).
pokemon_form(persian,default).
pokemon_form(psyduck,default).
pokemon_form(golduck,default).
pokemon_form(mankey,default).
pokemon_form(primeape,default).
pokemon_form(growlithe,default).
pokemon_form(arcanine,default).
pokemon_form(poliwag,default).
pokemon_form(poliwhirl,default).
pokemon_form(poliwrath,default).
pokemon_form(abra,default).
pokemon_form(kadabra,default).
pokemon_form(alakazam,default).
pokemon_form(machop,default).
pokemon_form(machoke,default).
pokemon_form(machamp,default).
pokemon_form(bellsprout,default).
pokemon_form(weepinbell,default).
pokemon_form(victreebel,default).
pokemon_form(tentacool,default).
pokemon_form(tentacruel,default).
pokemon_form(geodude,default).
pokemon_form(graveler,default).
pokemon_form(golem,default).
pokemon_form(ponyta,default).
pokemon_form(rapidash,default).
pokemon_form(slowpoke,default).
pokemon_form(slowbro,default).
pokemon_form(magnemite,default).
pokemon_form(magneton,default).
pokemon_form(farfetchd,default).
pokemon_form(doduo,default).
pokemon_form(dodrio,default).
pokemon_form(seel,default).
pokemon_form(dewgong,default).
pokemon_form(grimer,default).
pokemon_form(muk,default).
pokemon_form(shellder,default).
pokemon_form(cloyster,default).
pokemon_form(gastly,default).
pokemon_form(haunter,default).
pokemon_form(gengar,default).
pokemon_form(onix,default).
pokemon_form(drowzee,default).
pokemon_form(hypno,default).
pokemon_form(krabby,default).
pokemon_form(kingler,default).
pokemon_form(voltorb,default).
pokemon_form(electrode,default).
pokemon_form(exeggcute,default).
pokemon_form(exeggutor,default).
pokemon_form(cubone,default).
pokemon_form(marowak,default).
pokemon_form(hitmonlee,default).
pokemon_form(hitmonchan,default).
pokemon_form(lickitung,default).
pokemon_form(koffing,default).
pokemon_form(weezing,default).
pokemon_form(rhyhorn,default).
pokemon_form(rhydon,default).
pokemon_form(chansey,default).
pokemon_form(tangela,default).
pokemon_form(kangaskhan,default).
pokemon_form(horsea,default).
pokemon_form(seadra,default).
pokemon_form(goldeen,default).
pokemon_form(seaking,default).
pokemon_form(staryu,default).
pokemon_form(starmie,default).
pokemon_form(mr-mime,default).
pokemon_form(scyther,default).
pokemon_form(jynx,default).
pokemon_form(electabuzz,default).
pokemon_form(magmar,default).
pokemon_form(pinsir,default).
pokemon_form(tauros,default).
pokemon_form(magikarp,default).
pokemon_form(gyarados,default).
pokemon_form(lapras,default).
pokemon_form(ditto,default).
pokemon_form(eevee,default).
pokemon_form(vaporeon,default).
pokemon_form(jolteon,default).
pokemon_form(flareon,default).
pokemon_form(porygon,default).
pokemon_form(omanyte,default).
pokemon_form(omastar,default).
pokemon_form(kabuto,default).
pokemon_form(kabutops,default).
pokemon_form(aerodactyl,default).
pokemon_form(snorlax,default).
pokemon_form(articuno,default).
pokemon_form(zapdos,default).
pokemon_form(moltres,default).
pokemon_form(dratini,default).
pokemon_form(dragonair,default).
pokemon_form(dragonite,default).
pokemon_form(mewtwo,default).
pokemon_form(mew,default).
pokemon_form(chikorita,default).
pokemon_form(bayleef,default).
pokemon_form(meganium,default).
pokemon_form(cyndaquil,default).
pokemon_form(quilava,default).
pokemon_form(typhlosion,default).
pokemon_form(totodile,default).
pokemon_form(croconaw,default).
pokemon_form(feraligatr,default).
pokemon_form(sentret,default).
pokemon_form(furret,default).
pokemon_form(hoothoot,default).
pokemon_form(noctowl,default).
pokemon_form(ledyba,default).
pokemon_form(ledian,default).
pokemon_form(spinarak,default).
pokemon_form(ariados,default).
pokemon_form(crobat,default).
pokemon_form(chinchou,default).
pokemon_form(lanturn,default).
pokemon_form(pichu,default).
pokemon_form(cleffa,default).
pokemon_form(igglybuff,default).
pokemon_form(togepi,default).
pokemon_form(togetic,default).
pokemon_form(natu,default).
pokemon_form(xatu,default).
pokemon_form(mareep,default).
pokemon_form(flaaffy,default).
pokemon_form(ampharos,default).
pokemon_form(bellossom,default).
pokemon_form(marill,default).
pokemon_form(azumarill,default).
pokemon_form(sudowoodo,default).
pokemon_form(politoed,default).
pokemon_form(hoppip,default).
pokemon_form(skiploom,default).
pokemon_form(jumpluff,default).
pokemon_form(aipom,default).
pokemon_form(sunkern,default).
pokemon_form(sunflora,default).
pokemon_form(yanma,default).
pokemon_form(wooper,default).
pokemon_form(quagsire,default).
pokemon_form(espeon,default).
pokemon_form(umbreon,default).
pokemon_form(murkrow,default).
pokemon_form(slowking,default).
pokemon_form(misdreavus,default).
pokemon_form(unown,default).
pokemon_form(wobbuffet,default).
pokemon_form(girafarig,default).
pokemon_form(pineco,default).
pokemon_form(forretress,default).
pokemon_form(dunsparce,default).
pokemon_form(gligar,default).
pokemon_form(steelix,default).
pokemon_form(snubbull,default).
pokemon_form(granbull,default).
pokemon_form(qwilfish,default).
pokemon_form(scizor,default).
pokemon_form(shuckle,default).
pokemon_form(heracross,default).
pokemon_form(sneasel,default).
pokemon_form(teddiursa,default).
pokemon_form(ursaring,default).
pokemon_form(slugma,default).
pokemon_form(magcargo,default).
pokemon_form(swinub,default).
pokemon_form(piloswine,default).
pokemon_form(corsola,default).
pokemon_form(remoraid,default).
pokemon_form(octillery,default).
pokemon_form(delibird,default).
pokemon_form(mantine,default).
pokemon_form(skarmory,default).
pokemon_form(houndour,default).
pokemon_form(houndoom,default).
pokemon_form(kingdra,default).
pokemon_form(phanpy,default).
pokemon_form(donphan,default).
pokemon_form(porygon2,default).
pokemon_form(stantler,default).
pokemon_form(smeargle,default).
pokemon_form(tyrogue,default).
pokemon_form(hitmontop,default).
pokemon_form(smoochum,default).
pokemon_form(elekid,default).
pokemon_form(magby,default).
pokemon_form(miltank,default).
pokemon_form(blissey,default).
pokemon_form(raikou,default).
pokemon_form(entei,default).
pokemon_form(suicune,default).
pokemon_form(larvitar,default).
pokemon_form(pupitar,default).
pokemon_form(tyranitar,default).
pokemon_form(lugia,default).
pokemon_form(ho-oh,default).
pokemon_form(celebi,default).
pokemon_form(treecko,default).
pokemon_form(grovyle,default).
pokemon_form(sceptile,default).
pokemon_form(torchic,default).
pokemon_form(combusken,default).
pokemon_form(blaziken,default).
pokemon_form(mudkip,default).
pokemon_form(marshtomp,default).
pokemon_form(swampert,default).
pokemon_form(poochyena,default).
pokemon_form(mightyena,default).
pokemon_form(zigzagoon,default).
pokemon_form(linoone,default).
pokemon_form(wurmple,default).
pokemon_form(silcoon,default).
pokemon_form(beautifly,default).
pokemon_form(cascoon,default).
pokemon_form(dustox,default).
pokemon_form(lotad,default).
pokemon_form(lombre,default).
pokemon_form(ludicolo,default).
pokemon_form(seedot,default).
pokemon_form(nuzleaf,default).
pokemon_form(shiftry,default).
pokemon_form(taillow,default).
pokemon_form(swellow,default).
pokemon_form(wingull,default).
pokemon_form(pelipper,default).
pokemon_form(ralts,default).
pokemon_form(kirlia,default).
pokemon_form(gardevoir,default).
pokemon_form(surskit,default).
pokemon_form(masquerain,default).
pokemon_form(shroomish,default).
pokemon_form(breloom,default).
pokemon_form(slakoth,default).
pokemon_form(vigoroth,default).
pokemon_form(slaking,default).
pokemon_form(nincada,default).
pokemon_form(ninjask,default).
pokemon_form(shedinja,default).
pokemon_form(whismur,default).
pokemon_form(loudred,default).
pokemon_form(exploud,default).
pokemon_form(makuhita,default).
pokemon_form(hariyama,default).
pokemon_form(azurill,default).
pokemon_form(nosepass,default).
pokemon_form(skitty,default).
pokemon_form(delcatty,default).
pokemon_form(sableye,default).
pokemon_form(mawile,default).
pokemon_form(aron,default).
pokemon_form(lairon,default).
pokemon_form(aggron,default).
pokemon_form(meditite,default).
pokemon_form(medicham,default).
pokemon_form(electrike,default).
pokemon_form(manectric,default).
pokemon_form(plusle,default).
pokemon_form(minun,default).
pokemon_form(volbeat,default).
pokemon_form(illumise,default).
pokemon_form(roselia,default).
pokemon_form(gulpin,default).
pokemon_form(swalot,default).
pokemon_form(carvanha,default).
pokemon_form(sharpedo,default).
pokemon_form(wailmer,default).
pokemon_form(wailord,default).
pokemon_form(numel,default).
pokemon_form(camerupt,default).
pokemon_form(torkoal,default).
pokemon_form(spoink,default).
pokemon_form(grumpig,default).
pokemon_form(spinda,default).
pokemon_form(trapinch,default).
pokemon_form(vibrava,default).
pokemon_form(flygon,default).
pokemon_form(cacnea,default).
pokemon_form(cacturne,default).
pokemon_form(swablu,default).
pokemon_form(altaria,default).
pokemon_form(zangoose,default).
pokemon_form(seviper,default).
pokemon_form(lunatone,default).
pokemon_form(solrock,default).
pokemon_form(barboach,default).
pokemon_form(whiscash,default).
pokemon_form(corphish,default).
pokemon_form(crawdaunt,default).
pokemon_form(baltoy,default).
pokemon_form(claydol,default).
pokemon_form(lileep,default).
pokemon_form(cradily,default).
pokemon_form(anorith,default).
pokemon_form(armaldo,default).
pokemon_form(feebas,default).
pokemon_form(milotic,default).
pokemon_form(castform,default).
pokemon_form(kecleon,default).
pokemon_form(shuppet,default).
pokemon_form(banette,default).
pokemon_form(duskull,default).
pokemon_form(dusclops,default).
pokemon_form(tropius,default).
pokemon_form(chimecho,default).
pokemon_form(absol,default).
pokemon_form(wynaut,default).
pokemon_form(snorunt,default).
pokemon_form(glalie,default).
pokemon_form(spheal,default).
pokemon_form(sealeo,default).
pokemon_form(walrein,default).
pokemon_form(clamperl,default).
pokemon_form(huntail,default).
pokemon_form(gorebyss,default).
pokemon_form(relicanth,default).
pokemon_form(luvdisc,default).
pokemon_form(bagon,default).
pokemon_form(shelgon,default).
pokemon_form(salamence,default).
pokemon_form(beldum,default).
pokemon_form(metang,default).
pokemon_form(metagross,default).
pokemon_form(regirock,default).
pokemon_form(regice,default).
pokemon_form(registeel,default).
pokemon_form(latias,default).
pokemon_form(latios,default).
pokemon_form(kyogre,default).
pokemon_form(groudon,default).
pokemon_form(rayquaza,default).
pokemon_form(jirachi,default).
pokemon_form(deoxys-normal,default).
pokemon_form(turtwig,default).
pokemon_form(grotle,default).
pokemon_form(torterra,default).
pokemon_form(chimchar,default).
pokemon_form(monferno,default).
pokemon_form(infernape,default).
pokemon_form(piplup,default).
pokemon_form(prinplup,default).
pokemon_form(empoleon,default).
pokemon_form(starly,default).
pokemon_form(staravia,default).
pokemon_form(staraptor,default).
pokemon_form(bidoof,default).
pokemon_form(bibarel,default).
pokemon_form(kricketot,default).
pokemon_form(kricketune,default).
pokemon_form(shinx,default).
pokemon_form(luxio,default).
pokemon_form(luxray,default).
pokemon_form(budew,default).
pokemon_form(roserade,default).
pokemon_form(cranidos,default).
pokemon_form(rampardos,default).
pokemon_form(shieldon,default).
pokemon_form(bastiodon,default).
pokemon_form(burmy,default).
pokemon_form(wormadam-plant,default).
pokemon_form(mothim,default).
pokemon_form(combee,default).
pokemon_form(vespiquen,default).
pokemon_form(pachirisu,default).
pokemon_form(buizel,default).
pokemon_form(floatzel,default).
pokemon_form(cherubi,default).
pokemon_form(cherrim,default).
pokemon_form(shellos,default).
pokemon_form(gastrodon,default).
pokemon_form(ambipom,default).
pokemon_form(drifloon,default).
pokemon_form(drifblim,default).
pokemon_form(buneary,default).
pokemon_form(lopunny,default).
pokemon_form(mismagius,default).
pokemon_form(honchkrow,default).
pokemon_form(glameow,default).
pokemon_form(purugly,default).
pokemon_form(chingling,default).
pokemon_form(stunky,default).
pokemon_form(skuntank,default).
pokemon_form(bronzor,default).
pokemon_form(bronzong,default).
pokemon_form(bonsly,default).
pokemon_form(mime-jr,default).
pokemon_form(happiny,default).
pokemon_form(chatot,default).
pokemon_form(spiritomb,default).
pokemon_form(gible,default).
pokemon_form(gabite,default).
pokemon_form(garchomp,default).
pokemon_form(munchlax,default).
pokemon_form(riolu,default).
pokemon_form(lucario,default).
pokemon_form(hippopotas,default).
pokemon_form(hippowdon,default).
pokemon_form(skorupi,default).
pokemon_form(drapion,default).
pokemon_form(croagunk,default).
pokemon_form(toxicroak,default).
pokemon_form(carnivine,default).
pokemon_form(finneon,default).
pokemon_form(lumineon,default).
pokemon_form(mantyke,default).
pokemon_form(snover,default).
pokemon_form(abomasnow,default).
pokemon_form(weavile,default).
pokemon_form(magnezone,default).
pokemon_form(lickilicky,default).
pokemon_form(rhyperior,default).
pokemon_form(tangrowth,default).
pokemon_form(electivire,default).
pokemon_form(magmortar,default).
pokemon_form(togekiss,default).
pokemon_form(yanmega,default).
pokemon_form(leafeon,default).
pokemon_form(glaceon,default).
pokemon_form(gliscor,default).
pokemon_form(mamoswine,default).
pokemon_form(porygon-z,default).
pokemon_form(gallade,default).
pokemon_form(probopass,default).
pokemon_form(dusknoir,default).
pokemon_form(froslass,default).
pokemon_form(rotom,default).
pokemon_form(uxie,default).
pokemon_form(mesprit,default).
pokemon_form(azelf,default).
pokemon_form(dialga,default).
pokemon_form(palkia,default).
pokemon_form(heatran,default).
pokemon_form(regigigas,default).
pokemon_form(giratina-altered,default).
pokemon_form(cresselia,default).
pokemon_form(phione,default).
pokemon_form(manaphy,default).
pokemon_form(darkrai,default).
pokemon_form(shaymin-land,default).
pokemon_form(arceus,default).
pokemon_form(victini,default).
pokemon_form(snivy,default).
pokemon_form(servine,default).
pokemon_form(serperior,default).
pokemon_form(tepig,default).
pokemon_form(pignite,default).
pokemon_form(emboar,default).
pokemon_form(oshawott,default).
pokemon_form(dewott,default).
pokemon_form(samurott,default).
pokemon_form(patrat,default).
pokemon_form(watchog,default).
pokemon_form(lillipup,default).
pokemon_form(herdier,default).
pokemon_form(stoutland,default).
pokemon_form(purrloin,default).
pokemon_form(liepard,default).
pokemon_form(pansage,default).
pokemon_form(simisage,default).
pokemon_form(pansear,default).
pokemon_form(simisear,default).
pokemon_form(panpour,default).
pokemon_form(simipour,default).
pokemon_form(munna,default).
pokemon_form(musharna,default).
pokemon_form(pidove,default).
pokemon_form(tranquill,default).
pokemon_form(unfezant,default).
pokemon_form(blitzle,default).
pokemon_form(zebstrika,default).
pokemon_form(roggenrola,default).
pokemon_form(boldore,default).
pokemon_form(gigalith,default).
pokemon_form(woobat,default).
pokemon_form(swoobat,default).
pokemon_form(drilbur,default).
pokemon_form(excadrill,default).
pokemon_form(audino,default).
pokemon_form(timburr,default).
pokemon_form(gurdurr,default).
pokemon_form(conkeldurr,default).
pokemon_form(tympole,default).
pokemon_form(palpitoad,default).
pokemon_form(seismitoad,default).
pokemon_form(throh,default).
pokemon_form(sawk,default).
pokemon_form(sewaddle,default).
pokemon_form(swadloon,default).
pokemon_form(leavanny,default).
pokemon_form(venipede,default).
pokemon_form(whirlipede,default).
pokemon_form(scolipede,default).
pokemon_form(cottonee,default).
pokemon_form(whimsicott,default).
pokemon_form(petilil,default).
pokemon_form(lilligant,default).
pokemon_form(basculin-red-striped,default).
pokemon_form(sandile,default).
pokemon_form(krokorok,default).
pokemon_form(krookodile,default).
pokemon_form(darumaka,default).
pokemon_form(darmanitan-standard,default).
pokemon_form(maractus,default).
pokemon_form(dwebble,default).
pokemon_form(crustle,default).
pokemon_form(scraggy,default).
pokemon_form(scrafty,default).
pokemon_form(sigilyph,default).
pokemon_form(yamask,default).
pokemon_form(cofagrigus,default).
pokemon_form(tirtouga,default).
pokemon_form(carracosta,default).
pokemon_form(archen,default).
pokemon_form(archeops,default).
pokemon_form(trubbish,default).
pokemon_form(garbodor,default).
pokemon_form(zorua,default).
pokemon_form(zoroark,default).
pokemon_form(minccino,default).
pokemon_form(cinccino,default).
pokemon_form(gothita,default).
pokemon_form(gothorita,default).
pokemon_form(gothitelle,default).
pokemon_form(solosis,default).
pokemon_form(duosion,default).
pokemon_form(reuniclus,default).
pokemon_form(ducklett,default).
pokemon_form(swanna,default).
pokemon_form(vanillite,default).
pokemon_form(vanillish,default).
pokemon_form(vanilluxe,default).
pokemon_form(deerling,default).
pokemon_form(sawsbuck,default).
pokemon_form(emolga,default).
pokemon_form(karrablast,default).
pokemon_form(escavalier,default).
pokemon_form(foongus,default).
pokemon_form(amoonguss,default).
pokemon_form(frillish,default).
pokemon_form(jellicent,default).
pokemon_form(alomomola,default).
pokemon_form(joltik,default).
pokemon_form(galvantula,default).
pokemon_form(ferroseed,default).
pokemon_form(ferrothorn,default).
pokemon_form(klink,default).
pokemon_form(klang,default).
pokemon_form(klinklang,default).
pokemon_form(tynamo,default).
pokemon_form(eelektrik,default).
pokemon_form(eelektross,default).
pokemon_form(elgyem,default).
pokemon_form(beheeyem,default).
pokemon_form(litwick,default).
pokemon_form(lampent,default).
pokemon_form(chandelure,default).
pokemon_form(axew,default).
pokemon_form(fraxure,default).
pokemon_form(haxorus,default).
pokemon_form(cubchoo,default).
pokemon_form(beartic,default).
pokemon_form(cryogonal,default).
pokemon_form(shelmet,default).
pokemon_form(accelgor,default).
pokemon_form(stunfisk,default).
pokemon_form(mienfoo,default).
pokemon_form(mienshao,default).
pokemon_form(druddigon,default).
pokemon_form(golett,default).
pokemon_form(golurk,default).
pokemon_form(pawniard,default).
pokemon_form(bisharp,default).
pokemon_form(bouffalant,default).
pokemon_form(rufflet,default).
pokemon_form(braviary,default).
pokemon_form(vullaby,default).
pokemon_form(mandibuzz,default).
pokemon_form(heatmor,default).
pokemon_form(durant,default).
pokemon_form(deino,default).
pokemon_form(zweilous,default).
pokemon_form(hydreigon,default).
pokemon_form(larvesta,default).
pokemon_form(volcarona,default).
pokemon_form(cobalion,default).
pokemon_form(terrakion,default).
pokemon_form(virizion,default).
pokemon_form(tornadus-incarnate,default).
pokemon_form(thundurus-incarnate,default).
pokemon_form(reshiram,default).
pokemon_form(zekrom,default).
pokemon_form(landorus-incarnate,default).
pokemon_form(kyurem,default).
pokemon_form(keldeo-ordinary,default).
pokemon_form(meloetta-aria,default).
pokemon_form(genesect,default).
pokemon_form(chespin,default).
pokemon_form(quilladin,default).
pokemon_form(chesnaught,default).
pokemon_form(fennekin,default).
pokemon_form(braixen,default).
pokemon_form(delphox,default).
pokemon_form(froakie,default).
pokemon_form(frogadier,default).
pokemon_form(greninja,default).
pokemon_form(bunnelby,default).
pokemon_form(diggersby,default).
pokemon_form(fletchling,default).
pokemon_form(fletchinder,default).
pokemon_form(talonflame,default).
pokemon_form(scatterbug,default).
pokemon_form(spewpa,default).
pokemon_form(vivillon,default).
pokemon_form(litleo,default).
pokemon_form(pyroar,default).
pokemon_form(flabebe,default).
pokemon_form(floette,default).
pokemon_form(florges,default).
pokemon_form(skiddo,default).
pokemon_form(gogoat,default).
pokemon_form(pancham,default).
pokemon_form(pangoro,default).
pokemon_form(furfrou,default).
pokemon_form(espurr,default).
pokemon_form(meowstic-male,default).
pokemon_form(honedge,default).
pokemon_form(doublade,default).
pokemon_form(aegislash-shield,default).
pokemon_form(spritzee,default).
pokemon_form(aromatisse,default).
pokemon_form(swirlix,default).
pokemon_form(slurpuff,default).
pokemon_form(inkay,default).
pokemon_form(malamar,default).
pokemon_form(binacle,default).
pokemon_form(barbaracle,default).
pokemon_form(skrelp,default).
pokemon_form(dragalge,default).
pokemon_form(clauncher,default).
pokemon_form(clawitzer,default).
pokemon_form(helioptile,default).
pokemon_form(heliolisk,default).
pokemon_form(tyrunt,default).
pokemon_form(tyrantrum,default).
pokemon_form(amaura,default).
pokemon_form(aurorus,default).
pokemon_form(sylveon,default).
pokemon_form(hawlucha,default).
pokemon_form(dedenne,default).
pokemon_form(carbink,default).
pokemon_form(goomy,default).
pokemon_form(sliggoo,default).
pokemon_form(goodra,default).
pokemon_form(klefki,default).
pokemon_form(phantump,default).
pokemon_form(trevenant,default).
pokemon_form(pumpkaboo-average,default).
pokemon_form(gourgeist-average,default).
pokemon_form(bergmite,default).
pokemon_form(avalugg,default).
pokemon_form(noibat,default).
pokemon_form(noivern,default).
pokemon_form(xerneas,default).
pokemon_form(yveltal,default).
pokemon_form(zygarde,default).
pokemon_form(diancie,default).
pokemon_form(hoopa,default).
pokemon_form(volcanion,default).
pokemon_form(deoxys-attack,default).
pokemon_form(deoxys-defense,default).
pokemon_form(deoxys-speed,default).
pokemon_form(wormadam-sandy,default).
pokemon_form(wormadam-trash,default).
pokemon_form(shaymin-sky,default).
pokemon_form(giratina-origin,default).
pokemon_form(rotom-heat,default).
pokemon_form(rotom-wash,default).
pokemon_form(rotom-frost,default).
pokemon_form(rotom-fan,default).
pokemon_form(rotom-mow,default).
pokemon_form(castform-sunny,battle_only).
pokemon_form(castform-rainy,battle_only).
pokemon_form(castform-snowy,battle_only).
pokemon_form(basculin-blue-striped,default).
pokemon_form(darmanitan-zen,battle_only).
pokemon_form(meloetta-pirouette,battle_only).
pokemon_form(tornadus-therian,default).
pokemon_form(thundurus-therian,default).
pokemon_form(landorus-therian,default).
pokemon_form(kyurem-black,default).
pokemon_form(kyurem-white,default).
pokemon_form(keldeo-resolute,default).
pokemon_form(meowstic-female,default).
pokemon_form(aegislash-blade,battle_only).
pokemon_form(pumpkaboo-small,default).
pokemon_form(pumpkaboo-large,default).
pokemon_form(pumpkaboo-super,default).
pokemon_form(gourgeist-small,default).
pokemon_form(gourgeist-large,default).
pokemon_form(gourgeist-super,default).
pokemon_form(venusaur-mega,battle_only).
pokemon_form(charizard-mega-x,battle_only).
pokemon_form(charizard-mega-y,battle_only).
pokemon_form(blastoise-mega,battle_only).
pokemon_form(alakazam-mega,battle_only).
pokemon_form(gengar-mega,battle_only).
pokemon_form(kangaskhan-mega,battle_only).
pokemon_form(pinsir-mega,battle_only).
pokemon_form(gyarados-mega,battle_only).
pokemon_form(aerodactyl-mega,battle_only).
pokemon_form(mewtwo-mega-x,battle_only).
pokemon_form(mewtwo-mega-y,battle_only).
pokemon_form(ampharos-mega,battle_only).
pokemon_form(scizor-mega,battle_only).
pokemon_form(heracross-mega,battle_only).
pokemon_form(houndoom-mega,battle_only).
pokemon_form(tyranitar-mega,battle_only).
pokemon_form(blaziken-mega,battle_only).
pokemon_form(gardevoir-mega,battle_only).
pokemon_form(mawile-mega,battle_only).
pokemon_form(aggron-mega,battle_only).
pokemon_form(medicham-mega,battle_only).
pokemon_form(manectric-mega,battle_only).
pokemon_form(banette-mega,battle_only).
pokemon_form(absol-mega,battle_only).
pokemon_form(garchomp-mega,battle_only).
pokemon_form(lucario-mega,battle_only).
pokemon_form(abomasnow-mega,battle_only).
pokemon_form(floette-eternal,default).
pokemon_form(latias-mega,battle_only).
pokemon_form(latios-mega,battle_only).
