%! pokemon_species(+Pokemon_form,+Species_name).
%
% Maps the variations of certain pokemon to a common species.
%
% Meowstic or Basculin for example have two different forms with different ability pools.
% Or rotom has different forms with different types.
% But these forms all belong to one species, which can be accessed by this predicate.
% 
% @arg Pokemon_form A pokemon form name
% @arg Species_name The species name of the pokemon
pokemon_species(bulbasaur,bulbasaur).
pokemon_species(ivysaur,ivysaur).
pokemon_species(venusaur,venusaur).
pokemon_species(charmander,charmander).
pokemon_species(charmeleon,charmeleon).
pokemon_species(charizard,charizard).
pokemon_species(squirtle,squirtle).
pokemon_species(wartortle,wartortle).
pokemon_species(blastoise,blastoise).
pokemon_species(caterpie,caterpie).
pokemon_species(metapod,metapod).
pokemon_species(butterfree,butterfree).
pokemon_species(weedle,weedle).
pokemon_species(kakuna,kakuna).
pokemon_species(beedrill,beedrill).
pokemon_species(pidgey,pidgey).
pokemon_species(pidgeotto,pidgeotto).
pokemon_species(pidgeot,pidgeot).
pokemon_species(rattata,rattata).
pokemon_species(raticate,raticate).
pokemon_species(spearow,spearow).
pokemon_species(fearow,fearow).
pokemon_species(ekans,ekans).
pokemon_species(arbok,arbok).
pokemon_species(pikachu,pikachu).
pokemon_species(raichu,raichu).
pokemon_species(sandshrew,sandshrew).
pokemon_species(sandslash,sandslash).
pokemon_species(nidoran-f,nidoran-f).
pokemon_species(nidorina,nidorina).
pokemon_species(nidoqueen,nidoqueen).
pokemon_species(nidoran-m,nidoran-m).
pokemon_species(nidorino,nidorino).
pokemon_species(nidoking,nidoking).
pokemon_species(clefairy,clefairy).
pokemon_species(clefable,clefable).
pokemon_species(vulpix,vulpix).
pokemon_species(ninetales,ninetales).
pokemon_species(jigglypuff,jigglypuff).
pokemon_species(wigglytuff,wigglytuff).
pokemon_species(zubat,zubat).
pokemon_species(golbat,golbat).
pokemon_species(oddish,oddish).
pokemon_species(gloom,gloom).
pokemon_species(vileplume,vileplume).
pokemon_species(paras,paras).
pokemon_species(parasect,parasect).
pokemon_species(venonat,venonat).
pokemon_species(venomoth,venomoth).
pokemon_species(diglett,diglett).
pokemon_species(dugtrio,dugtrio).
pokemon_species(meowth,meowth).
pokemon_species(persian,persian).
pokemon_species(psyduck,psyduck).
pokemon_species(golduck,golduck).
pokemon_species(mankey,mankey).
pokemon_species(primeape,primeape).
pokemon_species(growlithe,growlithe).
pokemon_species(arcanine,arcanine).
pokemon_species(poliwag,poliwag).
pokemon_species(poliwhirl,poliwhirl).
pokemon_species(poliwrath,poliwrath).
pokemon_species(abra,abra).
pokemon_species(kadabra,kadabra).
pokemon_species(alakazam,alakazam).
pokemon_species(machop,machop).
pokemon_species(machoke,machoke).
pokemon_species(machamp,machamp).
pokemon_species(bellsprout,bellsprout).
pokemon_species(weepinbell,weepinbell).
pokemon_species(victreebel,victreebel).
pokemon_species(tentacool,tentacool).
pokemon_species(tentacruel,tentacruel).
pokemon_species(geodude,geodude).
pokemon_species(graveler,graveler).
pokemon_species(golem,golem).
pokemon_species(ponyta,ponyta).
pokemon_species(rapidash,rapidash).
pokemon_species(slowpoke,slowpoke).
pokemon_species(slowbro,slowbro).
pokemon_species(magnemite,magnemite).
pokemon_species(magneton,magneton).
pokemon_species(farfetchd,farfetchd).
pokemon_species(doduo,doduo).
pokemon_species(dodrio,dodrio).
pokemon_species(seel,seel).
pokemon_species(dewgong,dewgong).
pokemon_species(grimer,grimer).
pokemon_species(muk,muk).
pokemon_species(shellder,shellder).
pokemon_species(cloyster,cloyster).
pokemon_species(gastly,gastly).
pokemon_species(haunter,haunter).
pokemon_species(gengar,gengar).
pokemon_species(onix,onix).
pokemon_species(drowzee,drowzee).
pokemon_species(hypno,hypno).
pokemon_species(krabby,krabby).
pokemon_species(kingler,kingler).
pokemon_species(voltorb,voltorb).
pokemon_species(electrode,electrode).
pokemon_species(exeggcute,exeggcute).
pokemon_species(exeggutor,exeggutor).
pokemon_species(cubone,cubone).
pokemon_species(marowak,marowak).
pokemon_species(hitmonlee,hitmonlee).
pokemon_species(hitmonchan,hitmonchan).
pokemon_species(lickitung,lickitung).
pokemon_species(koffing,koffing).
pokemon_species(weezing,weezing).
pokemon_species(rhyhorn,rhyhorn).
pokemon_species(rhydon,rhydon).
pokemon_species(chansey,chansey).
pokemon_species(tangela,tangela).
pokemon_species(kangaskhan,kangaskhan).
pokemon_species(horsea,horsea).
pokemon_species(seadra,seadra).
pokemon_species(goldeen,goldeen).
pokemon_species(seaking,seaking).
pokemon_species(staryu,staryu).
pokemon_species(starmie,starmie).
pokemon_species(mr-mime,mr-mime).
pokemon_species(scyther,scyther).
pokemon_species(jynx,jynx).
pokemon_species(electabuzz,electabuzz).
pokemon_species(magmar,magmar).
pokemon_species(pinsir,pinsir).
pokemon_species(tauros,tauros).
pokemon_species(magikarp,magikarp).
pokemon_species(gyarados,gyarados).
pokemon_species(lapras,lapras).
pokemon_species(ditto,ditto).
pokemon_species(eevee,eevee).
pokemon_species(vaporeon,vaporeon).
pokemon_species(jolteon,jolteon).
pokemon_species(flareon,flareon).
pokemon_species(porygon,porygon).
pokemon_species(omanyte,omanyte).
pokemon_species(omastar,omastar).
pokemon_species(kabuto,kabuto).
pokemon_species(kabutops,kabutops).
pokemon_species(aerodactyl,aerodactyl).
pokemon_species(snorlax,snorlax).
pokemon_species(articuno,articuno).
pokemon_species(zapdos,zapdos).
pokemon_species(moltres,moltres).
pokemon_species(dratini,dratini).
pokemon_species(dragonair,dragonair).
pokemon_species(dragonite,dragonite).
pokemon_species(mewtwo,mewtwo).
pokemon_species(mew,mew).
pokemon_species(chikorita,chikorita).
pokemon_species(bayleef,bayleef).
pokemon_species(meganium,meganium).
pokemon_species(cyndaquil,cyndaquil).
pokemon_species(quilava,quilava).
pokemon_species(typhlosion,typhlosion).
pokemon_species(totodile,totodile).
pokemon_species(croconaw,croconaw).
pokemon_species(feraligatr,feraligatr).
pokemon_species(sentret,sentret).
pokemon_species(furret,furret).
pokemon_species(hoothoot,hoothoot).
pokemon_species(noctowl,noctowl).
pokemon_species(ledyba,ledyba).
pokemon_species(ledian,ledian).
pokemon_species(spinarak,spinarak).
pokemon_species(ariados,ariados).
pokemon_species(crobat,crobat).
pokemon_species(chinchou,chinchou).
pokemon_species(lanturn,lanturn).
pokemon_species(pichu,pichu).
pokemon_species(cleffa,cleffa).
pokemon_species(igglybuff,igglybuff).
pokemon_species(togepi,togepi).
pokemon_species(togetic,togetic).
pokemon_species(natu,natu).
pokemon_species(xatu,xatu).
pokemon_species(mareep,mareep).
pokemon_species(flaaffy,flaaffy).
pokemon_species(ampharos,ampharos).
pokemon_species(bellossom,bellossom).
pokemon_species(marill,marill).
pokemon_species(azumarill,azumarill).
pokemon_species(sudowoodo,sudowoodo).
pokemon_species(politoed,politoed).
pokemon_species(hoppip,hoppip).
pokemon_species(skiploom,skiploom).
pokemon_species(jumpluff,jumpluff).
pokemon_species(aipom,aipom).
pokemon_species(sunkern,sunkern).
pokemon_species(sunflora,sunflora).
pokemon_species(yanma,yanma).
pokemon_species(wooper,wooper).
pokemon_species(quagsire,quagsire).
pokemon_species(espeon,espeon).
pokemon_species(umbreon,umbreon).
pokemon_species(murkrow,murkrow).
pokemon_species(slowking,slowking).
pokemon_species(misdreavus,misdreavus).
pokemon_species(unown,unown).
pokemon_species(wobbuffet,wobbuffet).
pokemon_species(girafarig,girafarig).
pokemon_species(pineco,pineco).
pokemon_species(forretress,forretress).
pokemon_species(dunsparce,dunsparce).
pokemon_species(gligar,gligar).
pokemon_species(steelix,steelix).
pokemon_species(snubbull,snubbull).
pokemon_species(granbull,granbull).
pokemon_species(qwilfish,qwilfish).
pokemon_species(scizor,scizor).
pokemon_species(shuckle,shuckle).
pokemon_species(heracross,heracross).
pokemon_species(sneasel,sneasel).
pokemon_species(teddiursa,teddiursa).
pokemon_species(ursaring,ursaring).
pokemon_species(slugma,slugma).
pokemon_species(magcargo,magcargo).
pokemon_species(swinub,swinub).
pokemon_species(piloswine,piloswine).
pokemon_species(corsola,corsola).
pokemon_species(remoraid,remoraid).
pokemon_species(octillery,octillery).
pokemon_species(delibird,delibird).
pokemon_species(mantine,mantine).
pokemon_species(skarmory,skarmory).
pokemon_species(houndour,houndour).
pokemon_species(houndoom,houndoom).
pokemon_species(kingdra,kingdra).
pokemon_species(phanpy,phanpy).
pokemon_species(donphan,donphan).
pokemon_species(porygon2,porygon2).
pokemon_species(stantler,stantler).
pokemon_species(smeargle,smeargle).
pokemon_species(tyrogue,tyrogue).
pokemon_species(hitmontop,hitmontop).
pokemon_species(smoochum,smoochum).
pokemon_species(elekid,elekid).
pokemon_species(magby,magby).
pokemon_species(miltank,miltank).
pokemon_species(blissey,blissey).
pokemon_species(raikou,raikou).
pokemon_species(entei,entei).
pokemon_species(suicune,suicune).
pokemon_species(larvitar,larvitar).
pokemon_species(pupitar,pupitar).
pokemon_species(tyranitar,tyranitar).
pokemon_species(lugia,lugia).
pokemon_species(ho-oh,ho-oh).
pokemon_species(celebi,celebi).
pokemon_species(treecko,treecko).
pokemon_species(grovyle,grovyle).
pokemon_species(sceptile,sceptile).
pokemon_species(torchic,torchic).
pokemon_species(combusken,combusken).
pokemon_species(blaziken,blaziken).
pokemon_species(mudkip,mudkip).
pokemon_species(marshtomp,marshtomp).
pokemon_species(swampert,swampert).
pokemon_species(poochyena,poochyena).
pokemon_species(mightyena,mightyena).
pokemon_species(zigzagoon,zigzagoon).
pokemon_species(linoone,linoone).
pokemon_species(wurmple,wurmple).
pokemon_species(silcoon,silcoon).
pokemon_species(beautifly,beautifly).
pokemon_species(cascoon,cascoon).
pokemon_species(dustox,dustox).
pokemon_species(lotad,lotad).
pokemon_species(lombre,lombre).
pokemon_species(ludicolo,ludicolo).
pokemon_species(seedot,seedot).
pokemon_species(nuzleaf,nuzleaf).
pokemon_species(shiftry,shiftry).
pokemon_species(taillow,taillow).
pokemon_species(swellow,swellow).
pokemon_species(wingull,wingull).
pokemon_species(pelipper,pelipper).
pokemon_species(ralts,ralts).
pokemon_species(kirlia,kirlia).
pokemon_species(gardevoir,gardevoir).
pokemon_species(surskit,surskit).
pokemon_species(masquerain,masquerain).
pokemon_species(shroomish,shroomish).
pokemon_species(breloom,breloom).
pokemon_species(slakoth,slakoth).
pokemon_species(vigoroth,vigoroth).
pokemon_species(slaking,slaking).
pokemon_species(nincada,nincada).
pokemon_species(ninjask,ninjask).
pokemon_species(shedinja,shedinja).
pokemon_species(whismur,whismur).
pokemon_species(loudred,loudred).
pokemon_species(exploud,exploud).
pokemon_species(makuhita,makuhita).
pokemon_species(hariyama,hariyama).
pokemon_species(azurill,azurill).
pokemon_species(nosepass,nosepass).
pokemon_species(skitty,skitty).
pokemon_species(delcatty,delcatty).
pokemon_species(sableye,sableye).
pokemon_species(mawile,mawile).
pokemon_species(aron,aron).
pokemon_species(lairon,lairon).
pokemon_species(aggron,aggron).
pokemon_species(meditite,meditite).
pokemon_species(medicham,medicham).
pokemon_species(electrike,electrike).
pokemon_species(manectric,manectric).
pokemon_species(plusle,plusle).
pokemon_species(minun,minun).
pokemon_species(volbeat,volbeat).
pokemon_species(illumise,illumise).
pokemon_species(roselia,roselia).
pokemon_species(gulpin,gulpin).
pokemon_species(swalot,swalot).
pokemon_species(carvanha,carvanha).
pokemon_species(sharpedo,sharpedo).
pokemon_species(wailmer,wailmer).
pokemon_species(wailord,wailord).
pokemon_species(numel,numel).
pokemon_species(camerupt,camerupt).
pokemon_species(torkoal,torkoal).
pokemon_species(spoink,spoink).
pokemon_species(grumpig,grumpig).
pokemon_species(spinda,spinda).
pokemon_species(trapinch,trapinch).
pokemon_species(vibrava,vibrava).
pokemon_species(flygon,flygon).
pokemon_species(cacnea,cacnea).
pokemon_species(cacturne,cacturne).
pokemon_species(swablu,swablu).
pokemon_species(altaria,altaria).
pokemon_species(zangoose,zangoose).
pokemon_species(seviper,seviper).
pokemon_species(lunatone,lunatone).
pokemon_species(solrock,solrock).
pokemon_species(barboach,barboach).
pokemon_species(whiscash,whiscash).
pokemon_species(corphish,corphish).
pokemon_species(crawdaunt,crawdaunt).
pokemon_species(baltoy,baltoy).
pokemon_species(claydol,claydol).
pokemon_species(lileep,lileep).
pokemon_species(cradily,cradily).
pokemon_species(anorith,anorith).
pokemon_species(armaldo,armaldo).
pokemon_species(feebas,feebas).
pokemon_species(milotic,milotic).
pokemon_species(castform,castform).
pokemon_species(kecleon,kecleon).
pokemon_species(shuppet,shuppet).
pokemon_species(banette,banette).
pokemon_species(duskull,duskull).
pokemon_species(dusclops,dusclops).
pokemon_species(tropius,tropius).
pokemon_species(chimecho,chimecho).
pokemon_species(absol,absol).
pokemon_species(wynaut,wynaut).
pokemon_species(snorunt,snorunt).
pokemon_species(glalie,glalie).
pokemon_species(spheal,spheal).
pokemon_species(sealeo,sealeo).
pokemon_species(walrein,walrein).
pokemon_species(clamperl,clamperl).
pokemon_species(huntail,huntail).
pokemon_species(gorebyss,gorebyss).
pokemon_species(relicanth,relicanth).
pokemon_species(luvdisc,luvdisc).
pokemon_species(bagon,bagon).
pokemon_species(shelgon,shelgon).
pokemon_species(salamence,salamence).
pokemon_species(beldum,beldum).
pokemon_species(metang,metang).
pokemon_species(metagross,metagross).
pokemon_species(regirock,regirock).
pokemon_species(regice,regice).
pokemon_species(registeel,registeel).
pokemon_species(latias,latias).
pokemon_species(latios,latios).
pokemon_species(kyogre,kyogre).
pokemon_species(groudon,groudon).
pokemon_species(rayquaza,rayquaza).
pokemon_species(jirachi,jirachi).
pokemon_species(deoxys-normal,deoxys).
pokemon_species(turtwig,turtwig).
pokemon_species(grotle,grotle).
pokemon_species(torterra,torterra).
pokemon_species(chimchar,chimchar).
pokemon_species(monferno,monferno).
pokemon_species(infernape,infernape).
pokemon_species(piplup,piplup).
pokemon_species(prinplup,prinplup).
pokemon_species(empoleon,empoleon).
pokemon_species(starly,starly).
pokemon_species(staravia,staravia).
pokemon_species(staraptor,staraptor).
pokemon_species(bidoof,bidoof).
pokemon_species(bibarel,bibarel).
pokemon_species(kricketot,kricketot).
pokemon_species(kricketune,kricketune).
pokemon_species(shinx,shinx).
pokemon_species(luxio,luxio).
pokemon_species(luxray,luxray).
pokemon_species(budew,budew).
pokemon_species(roserade,roserade).
pokemon_species(cranidos,cranidos).
pokemon_species(rampardos,rampardos).
pokemon_species(shieldon,shieldon).
pokemon_species(bastiodon,bastiodon).
pokemon_species(burmy,burmy).
pokemon_species(wormadam-plant,wormadam).
pokemon_species(mothim,mothim).
pokemon_species(combee,combee).
pokemon_species(vespiquen,vespiquen).
pokemon_species(pachirisu,pachirisu).
pokemon_species(buizel,buizel).
pokemon_species(floatzel,floatzel).
pokemon_species(cherubi,cherubi).
pokemon_species(cherrim,cherrim).
pokemon_species(shellos,shellos).
pokemon_species(gastrodon,gastrodon).
pokemon_species(ambipom,ambipom).
pokemon_species(drifloon,drifloon).
pokemon_species(drifblim,drifblim).
pokemon_species(buneary,buneary).
pokemon_species(lopunny,lopunny).
pokemon_species(mismagius,mismagius).
pokemon_species(honchkrow,honchkrow).
pokemon_species(glameow,glameow).
pokemon_species(purugly,purugly).
pokemon_species(chingling,chingling).
pokemon_species(stunky,stunky).
pokemon_species(skuntank,skuntank).
pokemon_species(bronzor,bronzor).
pokemon_species(bronzong,bronzong).
pokemon_species(bonsly,bonsly).
pokemon_species(mime-jr,mime-jr).
pokemon_species(happiny,happiny).
pokemon_species(chatot,chatot).
pokemon_species(spiritomb,spiritomb).
pokemon_species(gible,gible).
pokemon_species(gabite,gabite).
pokemon_species(garchomp,garchomp).
pokemon_species(munchlax,munchlax).
pokemon_species(riolu,riolu).
pokemon_species(lucario,lucario).
pokemon_species(hippopotas,hippopotas).
pokemon_species(hippowdon,hippowdon).
pokemon_species(skorupi,skorupi).
pokemon_species(drapion,drapion).
pokemon_species(croagunk,croagunk).
pokemon_species(toxicroak,toxicroak).
pokemon_species(carnivine,carnivine).
pokemon_species(finneon,finneon).
pokemon_species(lumineon,lumineon).
pokemon_species(mantyke,mantyke).
pokemon_species(snover,snover).
pokemon_species(abomasnow,abomasnow).
pokemon_species(weavile,weavile).
pokemon_species(magnezone,magnezone).
pokemon_species(lickilicky,lickilicky).
pokemon_species(rhyperior,rhyperior).
pokemon_species(tangrowth,tangrowth).
pokemon_species(electivire,electivire).
pokemon_species(magmortar,magmortar).
pokemon_species(togekiss,togekiss).
pokemon_species(yanmega,yanmega).
pokemon_species(leafeon,leafeon).
pokemon_species(glaceon,glaceon).
pokemon_species(gliscor,gliscor).
pokemon_species(mamoswine,mamoswine).
pokemon_species(porygon-z,porygon-z).
pokemon_species(gallade,gallade).
pokemon_species(probopass,probopass).
pokemon_species(dusknoir,dusknoir).
pokemon_species(froslass,froslass).
pokemon_species(rotom,rotom).
pokemon_species(uxie,uxie).
pokemon_species(mesprit,mesprit).
pokemon_species(azelf,azelf).
pokemon_species(dialga,dialga).
pokemon_species(palkia,palkia).
pokemon_species(heatran,heatran).
pokemon_species(regigigas,regigigas).
pokemon_species(giratina-altered,giratina).
pokemon_species(cresselia,cresselia).
pokemon_species(phione,phione).
pokemon_species(manaphy,manaphy).
pokemon_species(darkrai,darkrai).
pokemon_species(shaymin-land,shaymin).
pokemon_species(arceus,arceus).
pokemon_species(victini,victini).
pokemon_species(snivy,snivy).
pokemon_species(servine,servine).
pokemon_species(serperior,serperior).
pokemon_species(tepig,tepig).
pokemon_species(pignite,pignite).
pokemon_species(emboar,emboar).
pokemon_species(oshawott,oshawott).
pokemon_species(dewott,dewott).
pokemon_species(samurott,samurott).
pokemon_species(patrat,patrat).
pokemon_species(watchog,watchog).
pokemon_species(lillipup,lillipup).
pokemon_species(herdier,herdier).
pokemon_species(stoutland,stoutland).
pokemon_species(purrloin,purrloin).
pokemon_species(liepard,liepard).
pokemon_species(pansage,pansage).
pokemon_species(simisage,simisage).
pokemon_species(pansear,pansear).
pokemon_species(simisear,simisear).
pokemon_species(panpour,panpour).
pokemon_species(simipour,simipour).
pokemon_species(munna,munna).
pokemon_species(musharna,musharna).
pokemon_species(pidove,pidove).
pokemon_species(tranquill,tranquill).
pokemon_species(unfezant,unfezant).
pokemon_species(blitzle,blitzle).
pokemon_species(zebstrika,zebstrika).
pokemon_species(roggenrola,roggenrola).
pokemon_species(boldore,boldore).
pokemon_species(gigalith,gigalith).
pokemon_species(woobat,woobat).
pokemon_species(swoobat,swoobat).
pokemon_species(drilbur,drilbur).
pokemon_species(excadrill,excadrill).
pokemon_species(audino,audino).
pokemon_species(timburr,timburr).
pokemon_species(gurdurr,gurdurr).
pokemon_species(conkeldurr,conkeldurr).
pokemon_species(tympole,tympole).
pokemon_species(palpitoad,palpitoad).
pokemon_species(seismitoad,seismitoad).
pokemon_species(throh,throh).
pokemon_species(sawk,sawk).
pokemon_species(sewaddle,sewaddle).
pokemon_species(swadloon,swadloon).
pokemon_species(leavanny,leavanny).
pokemon_species(venipede,venipede).
pokemon_species(whirlipede,whirlipede).
pokemon_species(scolipede,scolipede).
pokemon_species(cottonee,cottonee).
pokemon_species(whimsicott,whimsicott).
pokemon_species(petilil,petilil).
pokemon_species(lilligant,lilligant).
pokemon_species(basculin-red-striped,basculin).
pokemon_species(sandile,sandile).
pokemon_species(krokorok,krokorok).
pokemon_species(krookodile,krookodile).
pokemon_species(darumaka,darumaka).
pokemon_species(darmanitan-standard,darmanitan).
pokemon_species(maractus,maractus).
pokemon_species(dwebble,dwebble).
pokemon_species(crustle,crustle).
pokemon_species(scraggy,scraggy).
pokemon_species(scrafty,scrafty).
pokemon_species(sigilyph,sigilyph).
pokemon_species(yamask,yamask).
pokemon_species(cofagrigus,cofagrigus).
pokemon_species(tirtouga,tirtouga).
pokemon_species(carracosta,carracosta).
pokemon_species(archen,archen).
pokemon_species(archeops,archeops).
pokemon_species(trubbish,trubbish).
pokemon_species(garbodor,garbodor).
pokemon_species(zorua,zorua).
pokemon_species(zoroark,zoroark).
pokemon_species(minccino,minccino).
pokemon_species(cinccino,cinccino).
pokemon_species(gothita,gothita).
pokemon_species(gothorita,gothorita).
pokemon_species(gothitelle,gothitelle).
pokemon_species(solosis,solosis).
pokemon_species(duosion,duosion).
pokemon_species(reuniclus,reuniclus).
pokemon_species(ducklett,ducklett).
pokemon_species(swanna,swanna).
pokemon_species(vanillite,vanillite).
pokemon_species(vanillish,vanillish).
pokemon_species(vanilluxe,vanilluxe).
pokemon_species(deerling,deerling).
pokemon_species(sawsbuck,sawsbuck).
pokemon_species(emolga,emolga).
pokemon_species(karrablast,karrablast).
pokemon_species(escavalier,escavalier).
pokemon_species(foongus,foongus).
pokemon_species(amoonguss,amoonguss).
pokemon_species(frillish,frillish).
pokemon_species(jellicent,jellicent).
pokemon_species(alomomola,alomomola).
pokemon_species(joltik,joltik).
pokemon_species(galvantula,galvantula).
pokemon_species(ferroseed,ferroseed).
pokemon_species(ferrothorn,ferrothorn).
pokemon_species(klink,klink).
pokemon_species(klang,klang).
pokemon_species(klinklang,klinklang).
pokemon_species(tynamo,tynamo).
pokemon_species(eelektrik,eelektrik).
pokemon_species(eelektross,eelektross).
pokemon_species(elgyem,elgyem).
pokemon_species(beheeyem,beheeyem).
pokemon_species(litwick,litwick).
pokemon_species(lampent,lampent).
pokemon_species(chandelure,chandelure).
pokemon_species(axew,axew).
pokemon_species(fraxure,fraxure).
pokemon_species(haxorus,haxorus).
pokemon_species(cubchoo,cubchoo).
pokemon_species(beartic,beartic).
pokemon_species(cryogonal,cryogonal).
pokemon_species(shelmet,shelmet).
pokemon_species(accelgor,accelgor).
pokemon_species(stunfisk,stunfisk).
pokemon_species(mienfoo,mienfoo).
pokemon_species(mienshao,mienshao).
pokemon_species(druddigon,druddigon).
pokemon_species(golett,golett).
pokemon_species(golurk,golurk).
pokemon_species(pawniard,pawniard).
pokemon_species(bisharp,bisharp).
pokemon_species(bouffalant,bouffalant).
pokemon_species(rufflet,rufflet).
pokemon_species(braviary,braviary).
pokemon_species(vullaby,vullaby).
pokemon_species(mandibuzz,mandibuzz).
pokemon_species(heatmor,heatmor).
pokemon_species(durant,durant).
pokemon_species(deino,deino).
pokemon_species(zweilous,zweilous).
pokemon_species(hydreigon,hydreigon).
pokemon_species(larvesta,larvesta).
pokemon_species(volcarona,volcarona).
pokemon_species(cobalion,cobalion).
pokemon_species(terrakion,terrakion).
pokemon_species(virizion,virizion).
pokemon_species(tornadus-incarnate,tornadus).
pokemon_species(thundurus-incarnate,thundurus).
pokemon_species(reshiram,reshiram).
pokemon_species(zekrom,zekrom).
pokemon_species(landorus-incarnate,landorus).
pokemon_species(kyurem,kyurem).
pokemon_species(keldeo-ordinary,keldeo).
pokemon_species(meloetta-aria,meloetta).
pokemon_species(genesect,genesect).
pokemon_species(chespin,chespin).
pokemon_species(quilladin,quilladin).
pokemon_species(chesnaught,chesnaught).
pokemon_species(fennekin,fennekin).
pokemon_species(braixen,braixen).
pokemon_species(delphox,delphox).
pokemon_species(froakie,froakie).
pokemon_species(frogadier,frogadier).
pokemon_species(greninja,greninja).
pokemon_species(bunnelby,bunnelby).
pokemon_species(diggersby,diggersby).
pokemon_species(fletchling,fletchling).
pokemon_species(fletchinder,fletchinder).
pokemon_species(talonflame,talonflame).
pokemon_species(scatterbug,scatterbug).
pokemon_species(spewpa,spewpa).
pokemon_species(vivillon,vivillon).
pokemon_species(litleo,litleo).
pokemon_species(pyroar,pyroar).
pokemon_species(flabebe,flabebe).
pokemon_species(floette,floette).
pokemon_species(florges,florges).
pokemon_species(skiddo,skiddo).
pokemon_species(gogoat,gogoat).
pokemon_species(pancham,pancham).
pokemon_species(pangoro,pangoro).
pokemon_species(furfrou,furfrou).
pokemon_species(espurr,espurr).
pokemon_species(meowstic-male,meowstic).
pokemon_species(honedge,honedge).
pokemon_species(doublade,doublade).
pokemon_species(aegislash-shield,aegislash).
pokemon_species(spritzee,spritzee).
pokemon_species(aromatisse,aromatisse).
pokemon_species(swirlix,swirlix).
pokemon_species(slurpuff,slurpuff).
pokemon_species(inkay,inkay).
pokemon_species(malamar,malamar).
pokemon_species(binacle,binacle).
pokemon_species(barbaracle,barbaracle).
pokemon_species(skrelp,skrelp).
pokemon_species(dragalge,dragalge).
pokemon_species(clauncher,clauncher).
pokemon_species(clawitzer,clawitzer).
pokemon_species(helioptile,helioptile).
pokemon_species(heliolisk,heliolisk).
pokemon_species(tyrunt,tyrunt).
pokemon_species(tyrantrum,tyrantrum).
pokemon_species(amaura,amaura).
pokemon_species(aurorus,aurorus).
pokemon_species(sylveon,sylveon).
pokemon_species(hawlucha,hawlucha).
pokemon_species(dedenne,dedenne).
pokemon_species(carbink,carbink).
pokemon_species(goomy,goomy).
pokemon_species(sliggoo,sliggoo).
pokemon_species(goodra,goodra).
pokemon_species(klefki,klefki).
pokemon_species(phantump,phantump).
pokemon_species(trevenant,trevenant).
pokemon_species(pumpkaboo-average,pumpkaboo).
pokemon_species(gourgeist-average,gourgeist).
pokemon_species(bergmite,bergmite).
pokemon_species(avalugg,avalugg).
pokemon_species(noibat,noibat).
pokemon_species(noivern,noivern).
pokemon_species(xerneas,xerneas).
pokemon_species(yveltal,yveltal).
pokemon_species(zygarde,zygarde).
pokemon_species(diancie,diancie).
pokemon_species(hoopa,hoopa).
pokemon_species(volcanion,volcanion).
pokemon_species(deoxys-attack,deoxys).
pokemon_species(deoxys-defense,deoxys).
pokemon_species(deoxys-speed,deoxys).
pokemon_species(wormadam-sandy,wormadam).
pokemon_species(wormadam-trash,wormadam).
pokemon_species(shaymin-sky,shaymin).
pokemon_species(giratina-origin,giratina).
pokemon_species(rotom-heat,rotom).
pokemon_species(rotom-wash,rotom).
pokemon_species(rotom-frost,rotom).
pokemon_species(rotom-fan,rotom).
pokemon_species(rotom-mow,rotom).
pokemon_species(castform-sunny,castform).
pokemon_species(castform-rainy,castform).
pokemon_species(castform-snowy,castform).
pokemon_species(basculin-blue-striped,basculin).
pokemon_species(darmanitan-zen,darmanitan).
pokemon_species(meloetta-pirouette,meloetta).
pokemon_species(tornadus-therian,tornadus).
pokemon_species(thundurus-therian,thundurus).
pokemon_species(landorus-therian,landorus).
pokemon_species(kyurem-black,kyurem).
pokemon_species(kyurem-white,kyurem).
pokemon_species(keldeo-resolute,keldeo).
pokemon_species(meowstic-female,meowstic).
pokemon_species(aegislash-blade,aegislash).
pokemon_species(pumpkaboo-small,pumpkaboo).
pokemon_species(pumpkaboo-large,pumpkaboo).
pokemon_species(pumpkaboo-super,pumpkaboo).
pokemon_species(gourgeist-small,gourgeist).
pokemon_species(gourgeist-large,gourgeist).
pokemon_species(gourgeist-super,gourgeist).
pokemon_species(venusaur-mega,venusaur).
pokemon_species(charizard-mega-x,charizard).
pokemon_species(charizard-mega-y,charizard).
pokemon_species(blastoise-mega,blastoise).
pokemon_species(alakazam-mega,alakazam).
pokemon_species(gengar-mega,gengar).
pokemon_species(kangaskhan-mega,kangaskhan).
pokemon_species(pinsir-mega,pinsir).
pokemon_species(gyarados-mega,gyarados).
pokemon_species(aerodactyl-mega,aerodactyl).
pokemon_species(mewtwo-mega-x,mewtwo).
pokemon_species(mewtwo-mega-y,mewtwo).
pokemon_species(ampharos-mega,ampharos).
pokemon_species(scizor-mega,scizor).
pokemon_species(heracross-mega,heracross).
pokemon_species(houndoom-mega,houndoom).
pokemon_species(tyranitar-mega,tyranitar).
pokemon_species(blaziken-mega,blaziken).
pokemon_species(gardevoir-mega,gardevoir).
pokemon_species(mawile-mega,mawile).
pokemon_species(aggron-mega,aggron).
pokemon_species(medicham-mega,medicham).
pokemon_species(manectric-mega,manectric).
pokemon_species(banette-mega,banette).
pokemon_species(absol-mega,absol).
pokemon_species(garchomp-mega,garchomp).
pokemon_species(lucario-mega,lucario).
pokemon_species(abomasnow-mega,abomasnow).
pokemon_species(floette-eternal,floette).
pokemon_species(latias-mega,latias).
pokemon_species(latios-mega,latios).
